In [3]:
from sfs.models import make_MLP, make_CNN
from sfs.training import create_training_data, train
from sfs.config import CNNConfig
import pandas as pd

In [ ]:
training_data = pd.read_csv("/Users/admin/Desktop/mini_projects/digit_recognition/data/train.csv")
X = training_data.drop(columns = ["label"])
y = training_data["label"]

Data = create_training_data(X,y)

learning_rates = [10**-k for k in range(1,6)]


CNN_results = dict()
MLP_results = dict()

cnn_conf = CNNConfig()

for lr in learning_rates:
    model = make_CNN(cnn_conf)
    res = train(model, Data, learning_rate = lr)
    CNN_results.append(res)

for lr in learning_rates:
    model = make_MLP()
    res = train(model, Data, learning_rate = lr)
    MLP_results[lr] = res

In [ ]:
for lr in learning_rates:
    print(lr)
    display(results[lr])

0.1

   epoch  train_loss  val_loss  val_accuracy
0      1    2.261176  0.890484      0.749762
1      2    0.793319  0.850448      0.717619
2      3    0.825726  0.847691      0.769762
3      4    0.898230  1.033512      0.686667
4      5    1.084100  1.095066      0.709286
5      6    1.036599  1.155638      0.683571
6      7    0.913984  1.078768      0.696548
7      8    0.972238  1.018616      0.687857
8      9    0.967601  1.251918      0.685595
9     10    0.981133  1.217457      0.674524

0.01

   epoch  train_loss  val_loss  val_accuracy
0      1    0.262034  0.178064      0.946548
1      2    0.137951  0.182578      0.949643
2      3    0.115244  0.153080      0.960000
3      4    0.094936  0.259946      0.941667
4      5    0.082059  0.204857      0.959881
5      6    0.085020  0.230047      0.954048
6      7    0.077935  0.248101      0.960952
7      8    0.066794  0.193539      0.965238
8      9    0.076498  0.255586      0.960595
9     10    0.066882  0.305086      0.958095

0.001

   epoch  train_loss  val_loss  val_accuracy
0      1    0.310386  0.171691      0.947738
1      2    0.119624  0.120168      0.965476
2      3    0.076856  0.100475      0.969762
3      4    0.050555  0.091572      0.971786
4      5    0.037485  0.088215      0.974643
5      6    0.024315  0.089733      0.973929
6      7    0.019244  0.101800      0.973452
7      8    0.013622  0.100867      0.972976
8      9    0.012098  0.112970      0.970119
9     10    0.009356  0.094003      0.976190

0.0001

   epoch  train_loss  val_loss  val_accuracy
0      1    0.773290  0.388773      0.893214
1      2    0.324210  0.306304      0.911548
2      3    0.264484  0.260702      0.926190
3      4    0.228113  0.234971      0.934643
4      5    0.199977  0.214536      0.938571
5      6    0.178058  0.195099      0.943452
6      7    0.159392  0.177915      0.948333
7      8    0.143399  0.166786      0.950357
8      9    0.129936  0.156938      0.955000
9     10    0.118263  0.146896      0.956905

1e-05

   epoch  train_loss  val_loss  val_accuracy
0      1    1.978737  1.624378      0.781786
1      2    1.312932  1.058600      0.820714
2      3    0.896391  0.774244      0.841786
3      4    0.687460  0.626245      0.858929
4      5    0.571896  0.539261      0.870238
5      6    0.500006  0.482702      0.881310
6      7    0.451643  0.443340      0.886667
7      8    0.417025  0.414623      0.891190
8      9    0.390887  0.392520      0.893690
9     10    0.370502  0.375273      0.898095